### ISSUE TITLE
Change the tracking algorithm

### ISSUE THREAD

**Issue by Ziemnono** [Ziemnono/LandmarkTracking_RGBD#9]
The current tracking algorithm is optical flow, you can try to tweak the parameters but I highly doubt that we can track landmarks with such a low FPS (Frame Per Seconds). What I propose:

- [ ] State of the art (not too big) of facial landmark tracking
- [ ] Investigate this method https://github.com/rpautrat/SuperPoint
- [ ] Replace the optical flow algorithm
